/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ngo2024;

import javax.swing.plaf.basic.BasicInternalFrameUI;
import oru.inf.InfDB;
import oru.inf.InfException;
import javax.swing.JPanel;
import javax.swing.*;
import java.awt.*;
import java.net.URL;



/**
 *
 * @author Filip
 */
public class Menu2 extends javax.swing.JInternalFrame {

    private InfDB idb;
    /**
     * Creates new form Menu1
     */
    public Menu2(InfDB idb) {
        initComponents();
        this.idb = idb;
        skapaTestMal();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        
    }

    private void skapaTestMal() {
    for (int hid = 1; hid <= 3; hid++) {
        JPanel malPanel = new JPanel();
        malPanel.setLayout(new BorderLayout());

        // Bild
        JLabel ikon = new JLabel();
        ikon.setHorizontalAlignment(SwingConstants.CENTER);
        String bildsökväg = "/ngo2024/Bilder/hallbarhetsmal" + hid + ".png";

        URL bildURL = getClass().getResource(bildsökväg);
        if (bildURL != null) {
            ikon.setIcon(new ImageIcon(bildURL));
        } else {
            ikon.setText("[Bild saknas]");
        }

        // Knapp
        JButton knapp = new JButton("Visa mer");
        int finalHid = hid; // behövs pga lambda
        knapp.addActionListener(e -> visaMalInfo(finalHid));

        // Lägg till i målpanelen
        malPanel.add(ikon, BorderLayout.CENTER);
        malPanel.add(knapp, BorderLayout.SOUTH);

        // Lägg till i huvudpanelen
        panelMal.add(malPanel);
    }

    panelMal.revalidate();
    panelMal.repaint();
}

    private void visaMalInfo(int hid) {
    try {
        String namn = idb.fetchSingle("SELECT namn FROM hallbarhetsmal WHERE hid = '" + hid + "'");
        String malnummer = idb.fetchSingle("SELECT malnummer FROM hallbarhetsmal WHERE hid = '" + hid + "'");
        String beskrivning = idb.fetchSingle("SELECT beskrivning FROM hallbarhetsmal WHERE hid = '" + hid + "'");
        String prioritet = idb.fetchSingle("SELECT prioritet FROM hallbarhetsmal WHERE hid = '" + hid + "'");

        String info = "Mål: " + namn + "\n"
                    + "Målnummer: " + malnummer + "\n"
                    + "Prioritet: " + prioritet + "\n\n"
                    + "Beskrivning:\n" + beskrivning;

        JOptionPane.showMessageDialog(this, info, "Information om Hållbarhetsmål", JOptionPane.INFORMATION_MESSAGE);
    } catch (InfException ex) {
        JOptionPane.showMessageDialog(this, "Fel vid hämtning: " + ex.getMessage());
    }
}

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jlabelingenfattigdom = new javax.swing.JLabel();
        jlabelingenhunger = new javax.swing.JLabel();
        jlabelgodhalsaochvalbefinnande = new javax.swing.JLabel();
        jlabelgodutbildning = new javax.swing.JLabel();
        jlabeljamstalldhet = new javax.swing.JLabel();
        jlabelrentvattenochsanitet = new javax.swing.JLabel();
        jlabelhallbarenergiforalla = new javax.swing.JLabel();
        jlabelanstandigaarbetsvillkor = new javax.swing.JLabel();
        jlabelhallbarindustri = new javax.swing.JLabel();
        jlabelminskadojamlikhet = new javax.swing.JLabel();
        jlabelhallbarastader = new javax.swing.JLabel();
        jlabelhallbarkonsumtion = new javax.swing.JLabel();
        jlabelbekampaklimatforandringar = new javax.swing.JLabel();
        jlabelhavochmarinaresurser = new javax.swing.JLabel();
        jlabelekosystemochbiologiskmangfald = new javax.swing.JLabel();
        jlabelfredligaochinkluderandesamhallen = new javax.swing.JLabel();
        jlabelgenomforandeochglobaltpartnerskap = new javax.swing.JLabel();
        jlabelglobalamalenlogo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        panelMal = new javax.swing.JPanel();

        setBackground(new java.awt.Color(153, 255, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Hållbarhetsmål");

        jlabelingenfattigdom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ngo2024/Bilder/hallbarhetsmal1.png"))); // NOI18N
        jlabelingenfattigdom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabelingenfattigdomMouseClicked(evt);
            }
        });

        jlabelingenhunger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ngo2024/Bilder/hallbarhetsmal2.png"))); // NOI18N

        jlabelgodhalsaochvalbefinnande.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ngo2024/Bilder/hallbarhetsmal3.png"))); // NOI18N

        jlabelgodutbildning.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ngo2024/Bilder/hallbarhetsmal4.png"))); // NOI18N

        jlabeljamstalldhet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ngo2024/Bilder/hallbarhetsmal5.png"))); // NOI18N

        jlabelrentvattenochsanitet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ngo2024/Bilder/hallbarhetsmal6.png"))); // NOI18N

        jlabelhallbarenergiforalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ngo2024/Bilder/hallbarhetsmal7.png"))); // NOI18N

        jlabelanstandigaarbetsvillkor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ngo2024/Bilder/hallbarhetsmal8.png"))); // NOI18N

        jlabelhallbarindustri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ngo2024/Bilder/hallbarhetsmal9.png"))); // NOI18N

        jlabelminskadojamlikhet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ngo2024/Bilder/hallbarhetsmal10.png"))); // NOI18N

        jlabelhallbarastader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ngo2024/Bilder/hallbarhetsmal11.png"))); // NOI18N

        jlabelhallbarkonsumtion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ngo2024/Bilder/hallbarhetsmal12.png"))); // NOI18N

        jlabelbekampaklimatforandringar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ngo2024/Bilder/hallbarhetsmal13.png"))); // NOI18N

        jlabelhavochmarinaresurser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ngo2024/Bilder/hallbarhetsmal14.png"))); // NOI18N

        jlabelekosystemochbiologiskmangfald.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ngo2024/Bilder/hallbarhetsmal15.png"))); // NOI18N

        jlabelfredligaochinkluderandesamhallen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ngo2024/Bilder/hallbarhetsmal17.png"))); // NOI18N

        jlabelgenomforandeochglobaltpartnerskap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ngo2024/Bilder/hallbarhetsmal17.png"))); // NOI18N

        jlabelglobalamalenlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ngo2024/Bilder/globalamalenlogo.png"))); // NOI18N

        jButton1.setText("Visa Mer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        panelMal.setLayout(new java.awt.GridLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panelMal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(192, 192, 192)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jlabelbekampaklimatforandringar)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jlabelingenfattigdom)
                                                .addComponent(jlabelhallbarenergiforalla))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(177, 177, 177)
                                        .addComponent(jButton1)))
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlabelingenhunger)
                                    .addComponent(jlabelanstandigaarbetsvillkor)
                                    .addComponent(jlabelhavochmarinaresurser))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlabelgodhalsaochvalbefinnande)
                                    .addComponent(jlabelhallbarindustri)
                                    .addComponent(jlabelekosystemochbiologiskmangfald))))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlabelgodutbildning)
                                .addGap(27, 27, 27)
                                .addComponent(jlabeljamstalldhet))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlabelminskadojamlikhet)
                                    .addComponent(jlabelfredligaochinkluderandesamhallen))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlabelgenomforandeochglobaltpartnerskap)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jlabelglobalamalenlogo))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlabelhallbarastader)
                                        .addGap(31, 31, 31)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlabelrentvattenochsanitet)
                                            .addComponent(jlabelhallbarkonsumtion))))))))
                .addContainerGap(653, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlabelingenfattigdom)
                    .addComponent(jlabelingenhunger)
                    .addComponent(jlabelgodhalsaochvalbefinnande)
                    .addComponent(jlabelgodutbildning)
                    .addComponent(jlabeljamstalldhet)
                    .addComponent(jlabelrentvattenochsanitet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlabelhallbarenergiforalla)
                    .addComponent(jlabelanstandigaarbetsvillkor)
                    .addComponent(jlabelhallbarindustri)
                    .addComponent(jlabelminskadojamlikhet)
                    .addComponent(jlabelhallbarastader)
                    .addComponent(jlabelhallbarkonsumtion))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlabelbekampaklimatforandringar)
                    .addComponent(jlabelhavochmarinaresurser)
                    .addComponent(jlabelekosystemochbiologiskmangfald)
                    .addComponent(jlabelfredligaochinkluderandesamhallen)
                    .addComponent(jlabelgenomforandeochglobaltpartnerskap)
                    .addComponent(jlabelglobalamalenlogo))
                .addGap(18, 18, 18)
                .addComponent(panelMal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 546, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlabelingenfattigdomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabelingenfattigdomMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlabelingenfattigdomMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jlabelanstandigaarbetsvillkor;
    private javax.swing.JLabel jlabelbekampaklimatforandringar;
    private javax.swing.JLabel jlabelekosystemochbiologiskmangfald;
    private javax.swing.JLabel jlabelfredligaochinkluderandesamhallen;
    private javax.swing.JLabel jlabelgenomforandeochglobaltpartnerskap;
    private javax.swing.JLabel jlabelglobalamalenlogo;
    private javax.swing.JLabel jlabelgodhalsaochvalbefinnande;
    private javax.swing.JLabel jlabelgodutbildning;
    private javax.swing.JLabel jlabelhallbarastader;
    private javax.swing.JLabel jlabelhallbarenergiforalla;
    private javax.swing.JLabel jlabelhallbarindustri;
    private javax.swing.JLabel jlabelhallbarkonsumtion;
    private javax.swing.JLabel jlabelhavochmarinaresurser;
    private javax.swing.JLabel jlabelingenfattigdom;
    private javax.swing.JLabel jlabelingenhunger;
    private javax.swing.JLabel jlabeljamstalldhet;
    private javax.swing.JLabel jlabelminskadojamlikhet;
    private javax.swing.JLabel jlabelrentvattenochsanitet;
    private javax.swing.JPanel panelMal;
    // End of variables declaration//GEN-END:variables
}
