/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ngo2024;

import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.HashMap;

/**
 *
 * @author Jonas
 */
public class Menu1 extends javax.swing.JInternalFrame {
    
    private InfDB idb;
    private int anvandarID;

    /**
     * Creates new form Menu1
     */
    public Menu1(InfDB idb, int anvandarID) {
        this.idb = idb;
        this.anvandarID = anvandarID;
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButtonMinaProjekt = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultatMinaProjekt = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(153, 153, 255));

        lbl1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl1.setText("Projekt");

        jButton2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jButton2.setText("Avdelningens projekt");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButtonMinaProjekt.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jButtonMinaProjekt.setText("Mina projekt");
        jButtonMinaProjekt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMinaProjektMouseClicked(evt);
            }
        });
        jButtonMinaProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMinaProjektActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jButton4.setText("Visa partners i mina projekt");

        jButton5.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jButton5.setText("Sök projekt efter datum");

        txtResultatMinaProjekt.setEditable(false);
        txtResultatMinaProjekt.setBackground(new java.awt.Color(153, 153, 255));
        txtResultatMinaProjekt.setColumns(20);
        txtResultatMinaProjekt.setLineWrap(true);
        txtResultatMinaProjekt.setRows(5);
        txtResultatMinaProjekt.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtResultatMinaProjekt);

        jScrollPane2.setViewportView(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonMinaProjekt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMinaProjekt)
                    .addComponent(jButton2)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(292, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMinaProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMinaProjektActionPerformed
try {
    //Testar hur det blir med ActionPerformed istället för mouseclick
    String sql = "SELECT * FROM projekt WHERE projektchef = " + anvandarID;
    System.out.println("SQL: " + sql);
    //här kan man skriva ut till en JTextArea eller tabell
    var resultat = idb.fetchRows(sql);
    for (HashMap<String, String> rad : resultat) {
        System.out.println(rad.get("projektnamn"));
        
        //felsökning nedan
        System.out.println("AnvändarID: " + anvandarID);
System.out.println("Antal träffar: " + resultat.size());
    }
} catch (InfException ex) {
    JOptionPane.showMessageDialog(null, "Kunde inte hämta projekt: " + ex.getMessage());
}  
    }//GEN-LAST:event_jButtonMinaProjektActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonMinaProjektMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMinaProjektMouseClicked
try {
    txtResultatMinaProjekt.setText(""); //Rensar gamla resultat
    
    String sql = "SELECT p.* " +
                 "FROM projekt p " +
                 "JOIN projekt_personal pp ON p.pid = pp.pid " +
                 "WHERE pp.aid = " + anvandarID + ";";
                
                 
    var resultat = idb.fetchRows(sql);
    
    if (resultat.isEmpty()) {
        txtResultatMinaProjekt.setText("Du är inte delaktig i några projekt.");
    } else{
        txtResultatMinaProjekt.append("Dina projekt: \n\n");
        for (HashMap<String, String> rad : resultat) {
            txtResultatMinaProjekt.append("Projekt: " + rad.get("projektnamn") + "\n");
                txtResultatMinaProjekt.append("Start: " + rad.get("startdatum") + "\n");
                txtResultatMinaProjekt.append("Status: " + rad.get("status") + "\n");
                txtResultatMinaProjekt.append("--------------------------\n");
    }   
    }
    
        
} catch (InfException ex) {
    JOptionPane.showMessageDialog(null, "Kunde inte hämta projekt: " + ex.getMessage());
}
    }//GEN-LAST:event_jButtonMinaProjektMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonMinaProjekt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl1;
    private javax.swing.JTextArea txtResultatMinaProjekt;
    // End of variables declaration//GEN-END:variables
}
