/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ngo2024;

import javax.swing.plaf.basic.BasicInternalFrameUI;
import oru.inf.InfDB;
import oru.inf.InfException;


/**
 *
 * @author Filip
 */
public class Menu2 extends javax.swing.JInternalFrame {

        private InfDB idb;
        private int anvandarID;
        private String aktuellHID;
        private String originalNamn;
        private String originalMalnummer;
        private String originalBeskrivning;
        private String originalPrioritet;



    /**
     * Creates new form Menu1
     */
    public Menu2(InfDB idb, int anvandarID, String roll) {
        initComponents();
        this.idb = idb;
        this.anvandarID = anvandarID;
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        kontrolleraRollOchVisaRedigering();
        tfNamn.setText("");
        tfMålnummer.setText("");
        tfBeskrivning.setText("");
        tfPrioritet.setText("");
    }

    private void kontrolleraRollOchVisaRedigering() {
    try {
        String sql = "SELECT * FROM admin WHERE aid = " + anvandarID;
        var resultat = idb.fetchRow(sql);

        if (resultat != null) {
            // Användaren är en handläggare
            jpRedigeringsruta.setVisible(true);
        } else {
            // Användaren är inte handläggare
            jpRedigeringsruta.setVisible(false);
        }
    } catch (InfException e) {
        System.err.println("Kunde inte hämta rollinformation: " + e.getMessage());
        jpRedigeringsruta.setVisible(false);
    }
}


    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlabelingenfattigdom = new javax.swing.JLabel();
        jlabelingenhunger = new javax.swing.JLabel();
        jlabelgodhalsaochvalbefinnande = new javax.swing.JLabel();
        jlabelgodutbildning = new javax.swing.JLabel();
        jlabeljamstalldhet = new javax.swing.JLabel();
        jlabelrentvattenochsanitet = new javax.swing.JLabel();
        jlabelhallbarenergiforalla = new javax.swing.JLabel();
        jlabelanstandigaarbetsvillkor = new javax.swing.JLabel();
        jlabelhallbarindustri = new javax.swing.JLabel();
        jlabelminskadojamlikhet = new javax.swing.JLabel();
        jlabelhallbarastader = new javax.swing.JLabel();
        jlabelhallbarkonsumtion = new javax.swing.JLabel();
        jlabelbekampaklimatforandringar = new javax.swing.JLabel();
        jlabelhavochmarinaresurser = new javax.swing.JLabel();
        jlabelekosystemochbiologiskmangfald = new javax.swing.JLabel();
        jlabelfredligaochinkluderandesamhallen = new javax.swing.JLabel();
        jlabelgenomforandeochglobaltpartnerskap = new javax.swing.JLabel();
        jlabelglobalamalenlogo = new javax.swing.JLabel();
        panelMal = new javax.swing.JPanel();
        lblNamn = new javax.swing.JLabel();
        lblMålnummer = new javax.swing.JLabel();
        lblBeskrivning = new javax.swing.JLabel();
        lblPrioritet = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        tfNamn = new javax.swing.JTextField();
        tfMålnummer = new javax.swing.JTextField();
        tfPrioritet = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfBeskrivning = new javax.swing.JTextArea();
        jpRedigeringsruta = new javax.swing.JPanel();
        btnRedigera = new javax.swing.JButton();
        btnSpara = new javax.swing.JButton();
        btnAvbryt = new javax.swing.JButton();
        lblredigeraInfo = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(153, 255, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Hållbarhetsmål");

        jlabelingenfattigdom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ngo2024/Bilder/hallbarhetsmal1.png"))); // NOI18N
        jlabelingenfattigdom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabelingenfattigdomMouseClicked(evt);
            }
        });

        jlabelingenhunger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ngo2024/Bilder/hallbarhetsmal2.png"))); // NOI18N
        jlabelingenhunger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabelingenhungerMouseClicked(evt);
            }
        });

        jlabelgodhalsaochvalbefinnande.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ngo2024/Bilder/hallbarhetsmal3.png"))); // NOI18N
        jlabelgodhalsaochvalbefinnande.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabelgodhalsaochvalbefinnandeMouseClicked(evt);
            }
        });

        jlabelgodutbildning.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ngo2024/Bilder/hallbarhetsmal4.png"))); // NOI18N
        jlabelgodutbildning.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabelgodutbildningMouseClicked(evt);
            }
        });

        jlabeljamstalldhet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ngo2024/Bilder/hallbarhetsmal5.png"))); // NOI18N
        jlabeljamstalldhet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabeljamstalldhetMouseClicked(evt);
            }
        });

        jlabelrentvattenochsanitet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ngo2024/Bilder/hallbarhetsmal6.png"))); // NOI18N
        jlabelrentvattenochsanitet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabelrentvattenochsanitetMouseClicked(evt);
            }
        });

        jlabelhallbarenergiforalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ngo2024/Bilder/hallbarhetsmal7.png"))); // NOI18N
        jlabelhallbarenergiforalla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabelhallbarenergiforallaMouseClicked(evt);
            }
        });

        jlabelanstandigaarbetsvillkor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ngo2024/Bilder/hallbarhetsmal8.png"))); // NOI18N
        jlabelanstandigaarbetsvillkor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabelanstandigaarbetsvillkorMouseClicked(evt);
            }
        });

        jlabelhallbarindustri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ngo2024/Bilder/hallbarhetsmal9.png"))); // NOI18N
        jlabelhallbarindustri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabelhallbarindustriMouseClicked(evt);
            }
        });

        jlabelminskadojamlikhet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ngo2024/Bilder/hallbarhetsmal10.png"))); // NOI18N
        jlabelminskadojamlikhet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabelminskadojamlikhetMouseClicked(evt);
            }
        });

        jlabelhallbarastader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ngo2024/Bilder/hallbarhetsmal11.png"))); // NOI18N
        jlabelhallbarastader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabelhallbarastaderMouseClicked(evt);
            }
        });

        jlabelhallbarkonsumtion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ngo2024/Bilder/hallbarhetsmal12.png"))); // NOI18N
        jlabelhallbarkonsumtion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabelhallbarkonsumtionMouseClicked(evt);
            }
        });

        jlabelbekampaklimatforandringar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ngo2024/Bilder/hallbarhetsmal13.png"))); // NOI18N
        jlabelbekampaklimatforandringar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabelbekampaklimatforandringarMouseClicked(evt);
            }
        });

        jlabelhavochmarinaresurser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ngo2024/Bilder/hallbarhetsmal14.png"))); // NOI18N
        jlabelhavochmarinaresurser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabelhavochmarinaresurserMouseClicked(evt);
            }
        });

        jlabelekosystemochbiologiskmangfald.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ngo2024/Bilder/hallbarhetsmal15.png"))); // NOI18N
        jlabelekosystemochbiologiskmangfald.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabelekosystemochbiologiskmangfaldMouseClicked(evt);
            }
        });

        jlabelfredligaochinkluderandesamhallen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ngo2024/Bilder/hallbarhetsmal16.png"))); // NOI18N
        jlabelfredligaochinkluderandesamhallen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabelfredligaochinkluderandesamhallenMouseClicked(evt);
            }
        });

        jlabelgenomforandeochglobaltpartnerskap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ngo2024/Bilder/hallbarhetsmal17.png"))); // NOI18N
        jlabelgenomforandeochglobaltpartnerskap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabelgenomforandeochglobaltpartnerskapMouseClicked(evt);
            }
        });

        jlabelglobalamalenlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ngo2024/Bilder/globalamalenlogo.png"))); // NOI18N

        panelMal.setLayout(new java.awt.GridLayout(1, 0));

        lblNamn.setText("Namn");

        lblMålnummer.setText("Målnummer");

        lblBeskrivning.setText("Beskrivning");

        lblPrioritet.setText("Prioritet");

        jTextField1.setText("Tryck på ett mål för att visa mer");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        tfNamn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNamnActionPerformed(evt);
            }
        });

        tfMålnummer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMålnummerActionPerformed(evt);
            }
        });

        tfBeskrivning.setColumns(20);
        tfBeskrivning.setLineWrap(true);
        tfBeskrivning.setRows(5);
        tfBeskrivning.setWrapStyleWord(true);
        tfBeskrivning.setAutoscrolls(false);
        jScrollPane1.setViewportView(tfBeskrivning);

        btnRedigera.setText("Redigera");
        btnRedigera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRedigeraActionPerformed(evt);
            }
        });

        btnSpara.setText("Spara");
        btnSpara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSparaActionPerformed(evt);
            }
        });

        btnAvbryt.setText("Avbryt");
        btnAvbryt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvbrytActionPerformed(evt);
            }
        });

        lblredigeraInfo.setText("Info");

        javax.swing.GroupLayout jpRedigeringsrutaLayout = new javax.swing.GroupLayout(jpRedigeringsruta);
        jpRedigeringsruta.setLayout(jpRedigeringsrutaLayout);
        jpRedigeringsrutaLayout.setHorizontalGroup(
            jpRedigeringsrutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRedigeringsrutaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpRedigeringsrutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAvbryt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpRedigeringsrutaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblredigeraInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSpara, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRedigera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpRedigeringsrutaLayout.setVerticalGroup(
            jpRedigeringsrutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRedigeringsrutaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRedigera)
                .addGap(18, 18, 18)
                .addComponent(btnSpara)
                .addGap(18, 18, 18)
                .addComponent(btnAvbryt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblredigeraInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrioritet, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMålnummer, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBeskrivning, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfMålnummer, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfPrioritet, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(245, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelMal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlabelbekampaklimatforandringar)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlabelingenfattigdom)
                                .addComponent(jlabelhallbarenergiforalla)))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlabelingenhunger)
                            .addComponent(jlabelanstandigaarbetsvillkor)
                            .addComponent(jlabelhavochmarinaresurser))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlabelgodhalsaochvalbefinnande)
                            .addComponent(jlabelhallbarindustri)
                            .addComponent(jlabelekosystemochbiologiskmangfald))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlabelgodutbildning)
                                .addGap(27, 27, 27)
                                .addComponent(jlabeljamstalldhet))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlabelminskadojamlikhet)
                                    .addComponent(jlabelfredligaochinkluderandesamhallen))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlabelgenomforandeochglobaltpartnerskap)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jlabelglobalamalenlogo))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlabelhallbarastader)
                                        .addGap(31, 31, 31)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlabelrentvattenochsanitet)
                                            .addComponent(jlabelhallbarkonsumtion))))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpRedigeringsruta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlabelingenfattigdom)
                            .addComponent(jlabelingenhunger)
                            .addComponent(jlabelgodhalsaochvalbefinnande)
                            .addComponent(jlabelgodutbildning)
                            .addComponent(jlabeljamstalldhet)
                            .addComponent(jlabelrentvattenochsanitet))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlabelhallbarenergiforalla)
                            .addComponent(jlabelanstandigaarbetsvillkor)
                            .addComponent(jlabelhallbarindustri)
                            .addComponent(jlabelminskadojamlikhet)
                            .addComponent(jlabelhallbarastader)
                            .addComponent(jlabelhallbarkonsumtion))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlabelbekampaklimatforandringar)
                            .addComponent(jlabelhavochmarinaresurser)
                            .addComponent(jlabelekosystemochbiologiskmangfald)
                            .addComponent(jlabelfredligaochinkluderandesamhallen)
                            .addComponent(jlabelgenomforandeochglobaltpartnerskap)
                            .addComponent(jlabelglobalamalenlogo)))
                    .addComponent(jpRedigeringsruta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(panelMal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMålnummer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfMålnummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addComponent(lblBeskrivning, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrioritet, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPrioritet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlabelingenfattigdomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabelingenfattigdomMouseClicked
        try {
            aktuellHID = "1"; //För att definiera platsen åt hållbarhetsHID för eventuell redigering av admin

            String namn = idb.fetchSingle("SELECT namn FROM hallbarhetsmal WHERE hid = '1'");
            String malnummer = idb.fetchSingle("SELECT malnummer FROM hallbarhetsmal WHERE hid = '1'");
            String beskrivning = idb.fetchSingle("SELECT beskrivning FROM hallbarhetsmal WHERE hid = '1'");
            String prioritet = idb.fetchSingle("SELECT prioritet FROM hallbarhetsmal WHERE hid = '1'");

            tfNamn.setText(namn);
            tfMålnummer.setText(malnummer);
            tfBeskrivning.setText(beskrivning);
            tfPrioritet.setText(prioritet);

        } catch (InfException ex) {
            System.out.println("Fel vid hämtning av mål: " + ex.getMessage());
        }
    }//GEN-LAST:event_jlabelingenfattigdomMouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void tfMålnummerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMålnummerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMålnummerActionPerformed

    private void jlabelingenhungerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabelingenhungerMouseClicked
        try {
            aktuellHID = "2"; //För att definiera platsen åt hållbarhetsHID för eventuell redigering av admin

            String namn = idb.fetchSingle("SELECT namn FROM hallbarhetsmal WHERE hid = '2'");
            String malnummer = idb.fetchSingle("SELECT malnummer FROM hallbarhetsmal WHERE hid = '2'");
            String beskrivning = idb.fetchSingle("SELECT beskrivning FROM hallbarhetsmal WHERE hid = '2'");
            String prioritet = idb.fetchSingle("SELECT prioritet FROM hallbarhetsmal WHERE hid = '2'");

            tfNamn.setText(namn);
            tfMålnummer.setText(malnummer);
            tfBeskrivning.setText(beskrivning);
            tfPrioritet.setText(prioritet);

        } catch (InfException ex) {
            System.out.println("Fel vid hämtning av mål: " + ex.getMessage());
        }
    }//GEN-LAST:event_jlabelingenhungerMouseClicked

    private void jlabelgodhalsaochvalbefinnandeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabelgodhalsaochvalbefinnandeMouseClicked
        try {
            aktuellHID = "3"; //För att definiera platsen åt hållbarhetsHID för eventuell redigering av admin
            
            String namn = idb.fetchSingle("SELECT namn FROM hallbarhetsmal WHERE hid = '3'");
            String malnummer = idb.fetchSingle("SELECT malnummer FROM hallbarhetsmal WHERE hid = '3'");
            String beskrivning = idb.fetchSingle("SELECT beskrivning FROM hallbarhetsmal WHERE hid = '3'");
            String prioritet = idb.fetchSingle("SELECT prioritet FROM hallbarhetsmal WHERE hid = '3'");

            tfNamn.setText(namn);
            tfMålnummer.setText(malnummer);
            tfBeskrivning.setText(beskrivning);
            tfPrioritet.setText(prioritet);

        } catch (InfException ex) {
            System.out.println("Fel vid hämtning av mål: " + ex.getMessage());
        }
    }//GEN-LAST:event_jlabelgodhalsaochvalbefinnandeMouseClicked

    private void jlabelgodutbildningMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabelgodutbildningMouseClicked
        try {
            aktuellHID = "4"; //För att definiera platsen åt hållbarhetsHID för eventuell redigering av admin

            String namn = idb.fetchSingle("SELECT namn FROM hallbarhetsmal WHERE hid = '4'");
            String malnummer = idb.fetchSingle("SELECT malnummer FROM hallbarhetsmal WHERE hid = '4'");
            String beskrivning = idb.fetchSingle("SELECT beskrivning FROM hallbarhetsmal WHERE hid = '4'");
            String prioritet = idb.fetchSingle("SELECT prioritet FROM hallbarhetsmal WHERE hid = '4'");

            tfNamn.setText(namn);
            tfMålnummer.setText(malnummer);
            tfBeskrivning.setText(beskrivning);
            tfPrioritet.setText(prioritet);

        } catch (InfException ex) {
            System.out.println("Fel vid hämtning av mål: " + ex.getMessage());
        }
    }//GEN-LAST:event_jlabelgodutbildningMouseClicked

    private void jlabeljamstalldhetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabeljamstalldhetMouseClicked
        try {
            aktuellHID = "5"; //För att definiera platsen åt hållbarhetsHID för eventuell redigering av admin
            
            String namn = idb.fetchSingle("SELECT namn FROM hallbarhetsmal WHERE hid = '5'");
            String malnummer = idb.fetchSingle("SELECT malnummer FROM hallbarhetsmal WHERE hid = '5'");
            String beskrivning = idb.fetchSingle("SELECT beskrivning FROM hallbarhetsmal WHERE hid = '5'");
            String prioritet = idb.fetchSingle("SELECT prioritet FROM hallbarhetsmal WHERE hid = '5'");

            tfNamn.setText(namn);
            tfMålnummer.setText(malnummer);
            tfBeskrivning.setText(beskrivning);
            tfPrioritet.setText(prioritet);

        } catch (InfException ex) {
            System.out.println("Fel vid hämtning av mål: " + ex.getMessage());
        }
    }//GEN-LAST:event_jlabeljamstalldhetMouseClicked

    private void jlabelrentvattenochsanitetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabelrentvattenochsanitetMouseClicked
        try {
            aktuellHID = "6"; //För att definiera platsen åt hållbarhetsHID för eventuell redigering av admin

            String namn = idb.fetchSingle("SELECT namn FROM hallbarhetsmal WHERE hid = '6'");
            String malnummer = idb.fetchSingle("SELECT malnummer FROM hallbarhetsmal WHERE hid = '6'");
            String beskrivning = idb.fetchSingle("SELECT beskrivning FROM hallbarhetsmal WHERE hid = '6'");
            String prioritet = idb.fetchSingle("SELECT prioritet FROM hallbarhetsmal WHERE hid = '6'");

            tfNamn.setText(namn);
            tfMålnummer.setText(malnummer);
            tfBeskrivning.setText(beskrivning);
            tfPrioritet.setText(prioritet);

        } catch (InfException ex) {
            System.out.println("Fel vid hämtning av mål: " + ex.getMessage());
        }
    }//GEN-LAST:event_jlabelrentvattenochsanitetMouseClicked

    private void jlabelhallbarenergiforallaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabelhallbarenergiforallaMouseClicked
        try {
            aktuellHID = "7"; //För att definiera platsen åt hållbarhetsHID för eventuell redigering av admin

            String namn = idb.fetchSingle("SELECT namn FROM hallbarhetsmal WHERE hid = '7'");
            String malnummer = idb.fetchSingle("SELECT malnummer FROM hallbarhetsmal WHERE hid = '7'");
            String beskrivning = idb.fetchSingle("SELECT beskrivning FROM hallbarhetsmal WHERE hid = '7'");
            String prioritet = idb.fetchSingle("SELECT prioritet FROM hallbarhetsmal WHERE hid = '7'");

            tfNamn.setText(namn);
            tfMålnummer.setText(malnummer);
            tfBeskrivning.setText(beskrivning);
            tfPrioritet.setText(prioritet);

        } catch (InfException ex) {
            System.out.println("Fel vid hämtning av mål: " + ex.getMessage());
        }
    }//GEN-LAST:event_jlabelhallbarenergiforallaMouseClicked

    private void jlabelanstandigaarbetsvillkorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabelanstandigaarbetsvillkorMouseClicked
        try {
            aktuellHID = "8"; //För att definiera platsen åt hållbarhetsHID för eventuell redigering av admin
        
            String namn = idb.fetchSingle("SELECT namn FROM hallbarhetsmal WHERE hid = '8'");
            String malnummer = idb.fetchSingle("SELECT malnummer FROM hallbarhetsmal WHERE hid = '8'");
            String beskrivning = idb.fetchSingle("SELECT beskrivning FROM hallbarhetsmal WHERE hid = '8'");
            String prioritet = idb.fetchSingle("SELECT prioritet FROM hallbarhetsmal WHERE hid = '8'");

            tfNamn.setText(namn);
            tfMålnummer.setText(malnummer);
            tfBeskrivning.setText(beskrivning);
            tfPrioritet.setText(prioritet);

        } catch (InfException ex) {
            System.out.println("Fel vid hämtning av mål: " + ex.getMessage());
        }
    }//GEN-LAST:event_jlabelanstandigaarbetsvillkorMouseClicked

    private void jlabelhallbarindustriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabelhallbarindustriMouseClicked
        try {
            aktuellHID = "9"; //För att definiera platsen åt hållbarhetsHID för eventuell redigering av admin

            String namn = idb.fetchSingle("SELECT namn FROM hallbarhetsmal WHERE hid = '9'");
            String malnummer = idb.fetchSingle("SELECT malnummer FROM hallbarhetsmal WHERE hid = '9'");
            String beskrivning = idb.fetchSingle("SELECT beskrivning FROM hallbarhetsmal WHERE hid = '9'");
            String prioritet = idb.fetchSingle("SELECT prioritet FROM hallbarhetsmal WHERE hid = '9'");

            tfNamn.setText(namn);
            tfMålnummer.setText(malnummer);
            tfBeskrivning.setText(beskrivning);
            tfPrioritet.setText(prioritet);

        } catch (InfException ex) {
            System.out.println("Fel vid hämtning av mål: " + ex.getMessage());
        }
    }//GEN-LAST:event_jlabelhallbarindustriMouseClicked

    private void jlabelminskadojamlikhetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabelminskadojamlikhetMouseClicked
        try {
            aktuellHID = "10"; //För att definiera platsen åt hållbarhetsHID för eventuell redigering av admin
            
            String namn = idb.fetchSingle("SELECT namn FROM hallbarhetsmal WHERE hid = '10'");
            String malnummer = idb.fetchSingle("SELECT malnummer FROM hallbarhetsmal WHERE hid = '10'");
            String beskrivning = idb.fetchSingle("SELECT beskrivning FROM hallbarhetsmal WHERE hid = '10'");
            String prioritet = idb.fetchSingle("SELECT prioritet FROM hallbarhetsmal WHERE hid = '10'");

            tfNamn.setText(namn);
            tfMålnummer.setText(malnummer);
            tfBeskrivning.setText(beskrivning);
            tfPrioritet.setText(prioritet);

        } catch (InfException ex) {
            System.out.println("Fel vid hämtning av mål: " + ex.getMessage());
        }
    }//GEN-LAST:event_jlabelminskadojamlikhetMouseClicked

    private void jlabelhallbarastaderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabelhallbarastaderMouseClicked
        try {
            aktuellHID = "11"; //För att definiera platsen åt hållbarhetsHID för eventuell redigering av admin

            String namn = idb.fetchSingle("SELECT namn FROM hallbarhetsmal WHERE hid = '11'");
            String malnummer = idb.fetchSingle("SELECT malnummer FROM hallbarhetsmal WHERE hid = '11'");
            String beskrivning = idb.fetchSingle("SELECT beskrivning FROM hallbarhetsmal WHERE hid = '11'");
            String prioritet = idb.fetchSingle("SELECT prioritet FROM hallbarhetsmal WHERE hid = '11'");

            tfNamn.setText(namn);
            tfMålnummer.setText(malnummer);
            tfBeskrivning.setText(beskrivning);
            tfPrioritet.setText(prioritet);

        } catch (InfException ex) {
            System.out.println("Fel vid hämtning av mål: " + ex.getMessage());
        }
    }//GEN-LAST:event_jlabelhallbarastaderMouseClicked

    private void jlabelhallbarkonsumtionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabelhallbarkonsumtionMouseClicked
        try {
            aktuellHID = "12"; //För att definiera platsen åt hållbarhetsHID för eventuell redigering av admin

            String namn = idb.fetchSingle("SELECT namn FROM hallbarhetsmal WHERE hid = '12'");
            String malnummer = idb.fetchSingle("SELECT malnummer FROM hallbarhetsmal WHERE hid = '12'");
            String beskrivning = idb.fetchSingle("SELECT beskrivning FROM hallbarhetsmal WHERE hid = '12'");
            String prioritet = idb.fetchSingle("SELECT prioritet FROM hallbarhetsmal WHERE hid = '12'");

            tfNamn.setText(namn);
            tfMålnummer.setText(malnummer);
            tfBeskrivning.setText(beskrivning);
            tfPrioritet.setText(prioritet);

        } catch (InfException ex) {
            System.out.println("Fel vid hämtning av mål: " + ex.getMessage());
        }
    }//GEN-LAST:event_jlabelhallbarkonsumtionMouseClicked

    private void jlabelbekampaklimatforandringarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabelbekampaklimatforandringarMouseClicked
        try {
            aktuellHID = "13"; //För att definiera platsen åt hållbarhetsHID för eventuell redigering av admin

            String namn = idb.fetchSingle("SELECT namn FROM hallbarhetsmal WHERE hid = '13'");
            String malnummer = idb.fetchSingle("SELECT malnummer FROM hallbarhetsmal WHERE hid = '13'");
            String beskrivning = idb.fetchSingle("SELECT beskrivning FROM hallbarhetsmal WHERE hid = '13'");
            String prioritet = idb.fetchSingle("SELECT prioritet FROM hallbarhetsmal WHERE hid = '13'");

            tfNamn.setText(namn);
            tfMålnummer.setText(malnummer);
            tfBeskrivning.setText(beskrivning);
            tfPrioritet.setText(prioritet);

        } catch (InfException ex) {
            System.out.println("Fel vid hämtning av mål: " + ex.getMessage());
        }
    }//GEN-LAST:event_jlabelbekampaklimatforandringarMouseClicked

    private void jlabelhavochmarinaresurserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabelhavochmarinaresurserMouseClicked
        try {
            aktuellHID = "14"; //För att definiera platsen åt hållbarhetsHID för eventuell redigering av admin

            String namn = idb.fetchSingle("SELECT namn FROM hallbarhetsmal WHERE hid = '14'");
            String malnummer = idb.fetchSingle("SELECT malnummer FROM hallbarhetsmal WHERE hid = '14'");
            String beskrivning = idb.fetchSingle("SELECT beskrivning FROM hallbarhetsmal WHERE hid = '14'");
            String prioritet = idb.fetchSingle("SELECT prioritet FROM hallbarhetsmal WHERE hid = '14'");

            tfNamn.setText(namn);
            tfMålnummer.setText(malnummer);
            tfBeskrivning.setText(beskrivning);
            tfPrioritet.setText(prioritet);

        } catch (InfException ex) {
            System.out.println("Fel vid hämtning av mål: " + ex.getMessage());
        }
    }//GEN-LAST:event_jlabelhavochmarinaresurserMouseClicked

    private void jlabelekosystemochbiologiskmangfaldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabelekosystemochbiologiskmangfaldMouseClicked
        try {
            aktuellHID = "15"; //För att definiera platsen åt hållbarhetsHID för eventuell redigering av admin

            String namn = idb.fetchSingle("SELECT namn FROM hallbarhetsmal WHERE hid = '15'");
            String malnummer = idb.fetchSingle("SELECT malnummer FROM hallbarhetsmal WHERE hid = '15'");
            String beskrivning = idb.fetchSingle("SELECT beskrivning FROM hallbarhetsmal WHERE hid = '15'");
            String prioritet = idb.fetchSingle("SELECT prioritet FROM hallbarhetsmal WHERE hid = '15'");

            tfNamn.setText(namn);
            tfMålnummer.setText(malnummer);
            tfBeskrivning.setText(beskrivning);
            tfPrioritet.setText(prioritet);

        } catch (InfException ex) {
            System.out.println("Fel vid hämtning av mål: " + ex.getMessage());
        }
    }//GEN-LAST:event_jlabelekosystemochbiologiskmangfaldMouseClicked

    private void jlabelfredligaochinkluderandesamhallenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabelfredligaochinkluderandesamhallenMouseClicked
        try {
            aktuellHID = "16"; //För att definiera platsen åt hållbarhetsHID för eventuell redigering av admin

            String namn = idb.fetchSingle("SELECT namn FROM hallbarhetsmal WHERE hid = '16'");
            String malnummer = idb.fetchSingle("SELECT malnummer FROM hallbarhetsmal WHERE hid = '16'");
            String beskrivning = idb.fetchSingle("SELECT beskrivning FROM hallbarhetsmal WHERE hid = '16'");
            String prioritet = idb.fetchSingle("SELECT prioritet FROM hallbarhetsmal WHERE hid = '16'");

            tfNamn.setText(namn);
            tfMålnummer.setText(malnummer);
            tfBeskrivning.setText(beskrivning);
            tfPrioritet.setText(prioritet);

        } catch (InfException ex) {
            System.out.println("Fel vid hämtning av mål: " + ex.getMessage());
        }
    }//GEN-LAST:event_jlabelfredligaochinkluderandesamhallenMouseClicked

    private void jlabelgenomforandeochglobaltpartnerskapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabelgenomforandeochglobaltpartnerskapMouseClicked
        try {
            aktuellHID = "17"; //För att definiera platsen åt hållbarhetsHID för eventuell redigering av admin

            String namn = idb.fetchSingle("SELECT namn FROM hallbarhetsmal WHERE hid = '17'");
            String malnummer = idb.fetchSingle("SELECT malnummer FROM hallbarhetsmal WHERE hid = '17'");
            String beskrivning = idb.fetchSingle("SELECT beskrivning FROM hallbarhetsmal WHERE hid = '17'");
            String prioritet = idb.fetchSingle("SELECT prioritet FROM hallbarhetsmal WHERE hid = '17'");

            tfNamn.setText(namn);
            tfMålnummer.setText(malnummer);
            tfBeskrivning.setText(beskrivning);
            tfPrioritet.setText(prioritet);

        } catch (InfException ex) {
            System.out.println("Fel vid hämtning av mål: " + ex.getMessage());
        }
    }//GEN-LAST:event_jlabelgenomforandeochglobaltpartnerskapMouseClicked

    private void tfNamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNamnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNamnActionPerformed

    private void btnRedigeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRedigeraActionPerformed
        // Förifyll med nuvarande värden
    String nuvarandeNamn = tfNamn.getText();
    String nuvarandeMalnummer = tfMålnummer.getText();
    String nuvarandeBeskrivning = tfBeskrivning.getText();
    String nuvarandePrioritet = tfPrioritet.getText();
    
    // Spara ursprungliga värden ifall man väljer att trycka Avbryt
    originalNamn = tfNamn.getText();
    originalMalnummer = tfMålnummer.getText();
    originalBeskrivning = tfBeskrivning.getText();
    originalPrioritet = tfPrioritet.getText();


    // Skapa inputfält för dialogen
    javax.swing.JTextField fNamn = new javax.swing.JTextField(nuvarandeNamn);
    javax.swing.JTextField fMalnummer = new javax.swing.JTextField(nuvarandeMalnummer);
    javax.swing.JTextField fBeskrivning = new javax.swing.JTextField(nuvarandeBeskrivning);
    javax.swing.JTextField fPrioritet = new javax.swing.JTextField(nuvarandePrioritet);

    Object[] meddelande = {
        "Namn:", fNamn,
        "Målnummer:", fMalnummer,
        "Beskrivning:", fBeskrivning,
        "Prioritet:", fPrioritet
    };

    int val = javax.swing.JOptionPane.showConfirmDialog(null, meddelande, "Redigera hållbarhetsmål", javax.swing.JOptionPane.OK_CANCEL_OPTION);

    if (val == javax.swing.JOptionPane.OK_OPTION) {
        // Sätt nya värden i textfälten
        tfNamn.setText(fNamn.getText());
        tfMålnummer.setText(fMalnummer.getText());
        tfBeskrivning.setText(fBeskrivning.getText());
        tfPrioritet.setText(fPrioritet.getText());
    }        
    }//GEN-LAST:event_btnRedigeraActionPerformed

    private void btnSparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaActionPerformed
            if (aktuellHID == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Inget hållbarhetsmål är valt.");
        return;
    }

    try {
        String namn = tfNamn.getText().trim();
        String malnummer = tfMålnummer.getText().trim();
        String beskrivning = tfBeskrivning.getText().trim();
        String prioritet = tfPrioritet.getText().trim();

        String sql = "UPDATE hallbarhetsmal SET " +
                     "namn = '" + namn + "', " +
                     "malnummer = '" + malnummer + "', " +
                     "beskrivning = '" + beskrivning + "', " +
                     "prioritet = '" + prioritet + "' " +
                     "WHERE hid = '" + aktuellHID + "'";

        idb.update(sql);

        javax.swing.JOptionPane.showMessageDialog(this, "Målet har uppdaterats!");
    } catch (InfException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Fel vid uppdatering: " + e.getMessage());
    }
    }//GEN-LAST:event_btnSparaActionPerformed

    private void btnAvbrytActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvbrytActionPerformed
        tfNamn.setText(originalNamn);
        tfMålnummer.setText(originalMalnummer);
        tfBeskrivning.setText(originalBeskrivning);
        tfPrioritet.setText(originalPrioritet);
    
        lblredigeraInfo.setText("Ändringar har ångrats.");        
    }//GEN-LAST:event_btnAvbrytActionPerformed

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvbryt;
    private javax.swing.JButton btnRedigera;
    private javax.swing.JButton btnSpara;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel jlabelanstandigaarbetsvillkor;
    private javax.swing.JLabel jlabelbekampaklimatforandringar;
    private javax.swing.JLabel jlabelekosystemochbiologiskmangfald;
    private javax.swing.JLabel jlabelfredligaochinkluderandesamhallen;
    private javax.swing.JLabel jlabelgenomforandeochglobaltpartnerskap;
    private javax.swing.JLabel jlabelglobalamalenlogo;
    private javax.swing.JLabel jlabelgodhalsaochvalbefinnande;
    private javax.swing.JLabel jlabelgodutbildning;
    private javax.swing.JLabel jlabelhallbarastader;
    private javax.swing.JLabel jlabelhallbarenergiforalla;
    private javax.swing.JLabel jlabelhallbarindustri;
    private javax.swing.JLabel jlabelhallbarkonsumtion;
    private javax.swing.JLabel jlabelhavochmarinaresurser;
    private javax.swing.JLabel jlabelingenfattigdom;
    private javax.swing.JLabel jlabelingenhunger;
    private javax.swing.JLabel jlabeljamstalldhet;
    private javax.swing.JLabel jlabelminskadojamlikhet;
    private javax.swing.JLabel jlabelrentvattenochsanitet;
    private javax.swing.JPanel jpRedigeringsruta;
    private javax.swing.JLabel lblBeskrivning;
    private javax.swing.JLabel lblMålnummer;
    private javax.swing.JLabel lblNamn;
    private javax.swing.JLabel lblPrioritet;
    private javax.swing.JLabel lblredigeraInfo;
    private javax.swing.JPanel panelMal;
    private javax.swing.JTextArea tfBeskrivning;
    private javax.swing.JTextField tfMålnummer;
    private javax.swing.JTextField tfNamn;
    private javax.swing.JTextField tfPrioritet;
    // End of variables declaration//GEN-END:variables
}


